Docs: en translation
YunYouJun/valaxy pull request #186
Opened 2023-02-19 20:23 UTC by Shimogawa

2023-02-19 21:03 UTC, YunYouJun requested changes

2023-02-19 21:03 UTC, YunYouJun commented on docs/pages/guide/post.md
> +## Front Matter
I think we can use `FrontMatter` directly for searching.

2023-02-19 21:03 UTC, YunYouJun commented on docs/pages/guide/page.md
> -## Frontmatter
I think we can use FrontMatter directly for searching.

2023-02-19 21:03 UTC, YunYouJun commented
That's amazing. Thanks for your work.

2023-02-20 01:07 UTC, flaribbit commented
好快

2023-02-20 04:45 UTC, YunYouJun approved these changes

2023-02-20 04:46 UTC, YunYouJun commented
Just a reference https://jekyllrb.com/docs/front-matter/ .

2023-02-20 04:46 UTC, merged