feat:Add support for group in the nav configuration of the press theme
YunYouJun/valaxy pull request #491
Opened 2024-12-20 08:01 UTC by jiaxinPiggy

### Description

### Linked Issues
https://github.com/YunYouJun/valaxy/issues/477

### Additional context

2024-12-21 09:10 UTC, YunYouJun requested changes
Can you just provide an example and screenshot preview?

For the example, I think we can apply it directly to the current document.

2024-12-21 09:10 UTC, YunYouJun commented on packages/valaxy-theme-press/types/index.d.ts
> +export interface NavItemChildren {
How about we align with the type of vitepress as much as possible?

https://github.com/vuejs/vitepress/commit/e2d4edf45b5ec890c088d3b0517b21a7b3eab9df

2024-12-21 10:23 UTC, jiaxinPiggy commented
Sorry, I don't know how to provide an example. I can provide some screenshots
<img width="935" alt="case1" src="https://github.com/user-attachments/assets/5c1c880c-54e1-4730-a6e1-13d0b4bc953a" />
<img width="943" alt="case2" src="https://github.com/user-attachments/assets/d14c68be-2bc5-4fde-b361-9da6548f9c94" />
<img width="536" alt="case3" src="https://github.com/user-attachments/assets/ad965ebd-7c80-4ba4-adc0-b3a066336167" />

2024-12-24 01:14 UTC, YunYouJun commented
Thanks!

2024-12-24 01:15 UTC, YunYouJun approved these changes

2024-12-24 01:15 UTC, merged